# Generated by Django 2.0.6 on 2018-07-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('analysed', models.BooleanField(default=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('monochrome', models.BooleanField(default=False)),
                ('b_w', models.BooleanField(default=False)),
                ('file_date', models.DateTimeField()),
                ('scan_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('repos', models.ManyToManyField(to='wop.ImageRepo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wop.ScreenSetup')),
                ('slide_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wop.SlideShow')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='screen_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wop.ScreenSetup'),
        ),
        migrations.AddField(
            model_name='image',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wop.ImageRepo'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='wop.Tag'),
        ),
    ]
