# Generated by Django 2.0.6 on 2018-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
