# Generated by Django 2.0.6 on 2018-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wop', '0002_auto_20180826_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='key',
            field=models.CharField(default='UNSET', max_length=20, unique=True),
        ),
    ]
