# Generated by Django 2.0.6 on 2018-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wop', '0003_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='status',
            field=models.CharField(default='NONE', max_length=4),
        ),
    ]
