# Generated by Django 2.0.6 on 2018-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wop', '0004_wall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_view',
            field=models.DateTimeField(null=True),
        ),
    ]
