# Generated by Django 2.0.6 on 2018-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wop', '0005_image_last_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
